const util = ateos.lazify({
  isNaN: "./is_nan",
  pathval: "./pathval",
  test: "./test",
  expectTypes: "./expect_types",
  getMessage: "./get_message",
  inspect: "./inspect",
  objDisplay: "./obj_display",
  flag: "./flag",
  transferFlags: "./transfer_flags",
  addProperty: "./add_property",
  addMethod: "./add_method",
  overwriteProperty: "./overwrite_property",
  overwriteMethod: "./overwrite_method",
  addChainableMethod: "./add_chainable_method",
  overwriteChainableMethod: "./overwrite_chainable_method",
  compareByInspect: "./compare_by_inspect",
  getName: "./get_func_name",
  getOwnEnumerablePropertySymbols: "./get_own_enumerable_property_symbols",
  getOwnEnumerableProperties: "./get_own_enumerable_properties",
  getEnumerableProperties: "./get_enumerable_properties",
  checkError: "./check_error",
  proxify: "./proxify",
  addLengthGuard: "./add_length_guard",
  isProxyEnabled: "./is_proxy_enabled",
  getActual: "./get_actual",
  getProperties: "./get_properties",
  eql: () => ateos.is.deepEqual,
  eqlArray: () => ateos.is.equalArrays,
  getPathInfo: () => util.pathval.getPathInfo,
  hasProperty: () => util.pathval.hasProperty
}, exports, require, {
  writable: true
});
