// Note: fs methods are in alphabetical order
export default [
  "access",
  "accessSync",
  "appendFile",
  "appendFileSync",
  "chmod",
  "chmodSync",
  "chown",
  "chownSync",
  "chownr", // extra
  "chownrSync", // extra
  "close",
  "closeSync",
  "copyFile",
  "copyFileSync",
  "createReadStream",
  "createWriteStream",
  "exists", // deprecated
  "existsSync",
  "fallocate", // extra
  "fallocateSync", // extra
  "fchmod",
  "fchmodSync",
  "fchown",
  "fchownSync",
  "fdatasync",
  "fdatasyncSync",
  "fstat",
  "fstatSync",
  "fsync",
  "fsyncSync",
  "ftruncate",
  "ftruncateSync",
  "futimes",
  "futimesSync",
  "lchmod",
  "lchmodSync",
  "lchown",
  "lchownSync",
  "link",
  "linkSync",
  "lseek", // extra
  "lseekSync", // extra
  "lstat",
  "lstatSync",
  "mkdir",
  "mkdirSync",
  "mkdtemp",
  "mkdtempSync",
  "mmap", // extra
  "mmapSync", // extra
  "open",
  "openSync",
  "read",
  "readdir",
  "readdirSync",
  "readFile",
  "readFileSync",
  "readlink",
  "readlinkSync",
  "readSync",
  "realpath",
  "realpathSync",
  "rename",
  "renameSync",
  "rmdir",
  "rmdirSync",
  "stat",
  "statSync",
  "symlink",
  "symlinkSync",
  "truncate",
  "truncateSync",
  "unlink",
  "unlinkSync",
  "utimes",
  "utimesSync",
  "write",
  "writeFile",
  "writeFileSync",
  "writeSync",
  "watch",
  "watchFile",
  "unwatchFile"
];
